let mapleader = " "

set hidden
set wildmenu
set wildmode+=longest,full
set ignorecase
set smartcase
set backspace=indent,eol,start
set nostartofline
set confirm
set mouse=a
set breakindent
set linebreak
set tabstop=8
set softtabstop=8
set autoindent
set shiftwidth=8
set undofile
set incsearch
set nomodeline
"set list
set lcs=nbsp:␣,eol:↲,tab:»\ ,trail:·,extends:›,precedes:‹,space:·
set foldlevelstart=20
set undofile
set completeopt=menu,menuone,preview,noselect,noinsert
set path+=**
set nrformats+=alpha
set guioptions+=k
set dictionary+=/usr/share/dict/words
set hlsearch
" set number
" set relativenumber
" set termguicolors

if has('nvim') || (v:version == 802 && has('patch4325')) || v:version > 802
  set wildoptions+=pum
endif

filetype plugin indent on

silent execute '!mkdir -p $HOME/.vim/backupdir/ $HOME/.vim/swp/ $HOME/.vim/undodir/'

" Double tailing slash stores files using full paths to avoid file name clashes
set backupdir=$HOME/.vim/backupdir//
set directory=$HOME/.vim/swp//
set undodir=$HOME/.vim/undodir//
set undofile

autocmd FileType gitcommit set textwidth=72
autocmd FileType gitcommit set colorcolumn=73

" Fix for slow startup time on Tmux
call serverlist()

" Git grep to quickfix list
command -nargs=+ Ggr execute 'Ggrep! -q' <q-args>

nnoremap <Up> :resize -2<CR>
nnoremap <Down> :resize +2<CR>
nnoremap <Left> :vertical resize -2<CR>
nnoremap <Right> :vertical resize +2<CR>
noremap <F6> :set list!<CR>
inoremap <F6> <C-o>:set list!<CR>
cnoremap <F6> <C-c>:set list!<CR>
noremap <F7> :mksession! Session.vim<CR>

syntax off

