vim.o.inccommand = 'nosplit'
vim.opt.hidden = true
vim.opt.wildmenu = true
vim.opt.wildmode = "list:longest,full"
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.backspace = "indent,eol,start"
vim.opt.startofline = false
vim.opt.confirm = true
vim.opt.mouse = 'a'
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.breakindent = true
vim.opt.linebreak = true
vim.opt.tabstop = 8
vim.opt.softtabstop = 8
vim.opt.autoindent = true
vim.opt.shiftwidth = 8
vim.opt.colorcolumn = "80"
vim.opt.updatetime = 200
vim.opt.undofile = true
vim.opt.incsearch = true
vim.opt.modeline = false
vim.opt.list = true
vim.opt.foldlevelstart = 20
vim.opt.undofile = true
vim.opt.completeopt = "menuone,noselect"
vim.opt.path = vim.opt.path + '**'
vim.opt.shortmess = vim.opt.shortmess + 'c'
vim.opt.nrformats = vim.opt.nrformats + 'alpha' + 'octal'
vim.opt.dictionary = vim.opt.dictionary + '/usr/share/dict/words'
--vim.opt.laststatus=1
--vim.cmd 'let g:gruvbox_material_transparent_background = 1'
--vim.o.termguicolors = true
--vim.opt.background = "dark"
--vim.cmd 'colorscheme gruvbox-material'
